[Metadata]
Name=Glassmorphism
Version=0.1
Author=chiyonn
Description=Frosted glass theme with depth and edge lighting

[InputPanel]
Font=JetBrainsMono Nerd Font 13
NormalColor=#bfbfbf
HighlightCandidateColor=#f2f2f2
HighlightColor=#f2f2f2
HighlightBackgroundColor=#444466
Spacing=3

[InputPanel/TextMargin]
Left=12
Right=12
Top=8
Bottom=8

[InputPanel/Background]
Image=panel.png

[InputPanel/Background/Margin]
Left=2
Right=2
Top=2
Bottom=2

[InputPanel/Highlight]
Color=#444466

[InputPanel/Highlight/Margin]
Left=12
Right=12
Top=8
Bottom=8

[Menu]
Font=JetBrainsMono Nerd Font 10
NormalColor=#bfbfbf
Spacing=3

[Menu/Background]
Image=panel.png

[Menu/Background/Margin]
Left=2
Right=2
Top=2
Bottom=2

[Menu/ContentMargin]
Left=2
Right=2
Top=2
Bottom=2

[Menu/Highlight]
Color=#444466

[Menu/Highlight/Margin]
Left=12
Right=12
Top=6
Bottom=6

[Menu/Separator]
Color=#333344

[Menu/CheckBox]
Image=radio.png

[Menu/SubMenu]
Image=arrow.png

[Menu/TextMargin]
Left=6
Right=6
Top=6
Bottom=6
